export const english = {
  login: "Login",
  BusinessPartner: "Signup as business partner",
  welcome:'Hi, Welcome back',
  email:'Email/Phone',
  password:'Password*',
  frpassword:'forget password',
  next:"NEXT",
  placeholder:"Enter Your Email/Phone",
  SignIn:'SIGN IN',
  SignGoogle:'Sign in with Google',
  CreatenewAccount:`don't have an account yet ?`,
  CreatenewAccount1:`join connect souq now !`,
  personalInformation: 'Personal information',
  personalDetails: 'Personal Information',
  enterPersonalDetails: 'Please enter your personal Information!',
  firstName: 'First name *',
  enterFirstName: 'Enter your first name',
  lastName: 'Last name*',
  enterLastName: 'Enter your last name',
  dateOfBirth: 'Date of birth*',
  designation: 'Date of birth*',
  back: 'Back',
  continue: 'Continue',
  contactDetail: 'Location Details',
  enterContactDetails: 'Please enter your personal details!',
  phoneNumber: 'Phone number',
  emailAddress: 'Email *',
  enterEmailAddress: 'Please enter your email address',
  personalLocation: 'Please enter your personal location',
  country: 'Country*',
  selectCountry: 'Select a country',
  city: 'City *',
  enterCity: 'Enter your city',
  register: 'Register',
  registrationSuccessful: 'Registration successful',
  enterOTP: 'Enter OTP',
  enterYourOTP: 'Enter your OTP',
  verifyOTP: 'Verify OTP',
  emailAlreadyRegistered: 'Email already registered',
  //   
  businessInfo: 'Business info',
  individualCompany: 'Individual / Company',
  enterBusinessInfo: 'Please enter your business information',
  individual: 'Individual',
  company: 'Company',
  previous: 'Previous',
  continueBtn: 'Continue',
  location: 'Location',
  enterBusinessLocation: 'Please enter your business location!',
  state: 'State',
  enterState: 'Enter your state',
  industry: 'Industry',
  enterBusinessIndustry: 'Please enter your business industry',
  companyDetails: 'Company details',
  companyName: 'Company name',
  enterCompanyName: 'Enter your company name',
  enterPostalCode: 'Enter your postal code',
  businessContact: 'Business contact',
  enterBusinessContact: 'Enter your business contact',
  businessEmail: 'Business email',
  enterBusinessEmail: 'Enter your business email',
  annualIncome: 'Annual income',
  enterAnnualIncome: 'Enter your annual income',
  companySize: 'Company size',
  enterCompanySize: 'Enter your company size',
  otherIndustry: 'Other industry',
  enterOtherIndustry: 'Enter your other industry',
  selectMinimumIndustries: 'Please select minimum 5 industries',
  enterMandatoryFields: 'Please enter mandatory fields',
//   
  userDetails: 'User details',
  addEmail: 'Add email',
  emails: 'Email',
  enterEmail: 'Enter your email/phone',
  addContact: 'Add contact',
  contact: 'Contact',
  enterContact: 'Enter your contact',
  addWebsite: 'Add website',
  website: 'Website',
  enterWebsite: 'Enter your website',
  loginToContinue: 'Login to continue',
  contactbusiness:'TO BECOME A CONNECTOR PARTNER, YOU MUST ADD 1 POTENTIAL CONTACT AS A REFERENCE AND CONTACT WILL BE VERIFIED',
  // 
  bankDetails: 'Bank details',
  transitNumber: 'Transit number',
  institutionNumber: 'Institution number',
  accountNumber: 'Account number',
  certifyBankDetails: 'I certify that provided bank details are correct',
  enterdesignation:'Enter your Designation',
  designation:'Designation*',
  registerDetails:'Please Enter Your User Details',
  // 
  home: 'Home',
  searchHere: 'search here',
  news: 'News',
  advertisement: 'Advertisement',
  post: 'Post',
  about: 'About',
  helpCenter: 'Help Center',
  privacyTerms: 'privacy & term',
  adChoices: 'Ad Choices',
  advertising: 'Advertising',
  businessServices: 'Business Services',
  getApp: 'Get the App',
  more: 'More',
  seeAll: 'see all',
  whatsOnYourMind: `what's on your mind?`,
  like: 'Like',
  comment: 'Comment',
  share: 'Share',
  complete: 'Complete',
  myItems: 'My items',
  management: 'Management',
  logout: 'Logout',
  tryPremiumFor: 'try premium for',
  see: 'see',
// Business-pagae
business: 'Business',
search: 'Search',
chats: 'Chats',
group: 'Group',
reply: 'Reply',
letsConnect: 'Let\'s connect',
filters: 'Filters',
selectIndustry: 'Select Industry',
sales: 'Sales',
rating: 'Rating',
sortBy: 'Sort by',
showResults: 'Show results',

// pavilion 
gPavilion: 'G-Pavilion',
selectCategory: 'Select category',
viewDetails: 'View details',
buyer: 'Buyer',
supplier: 'Supplier',
enterLocation: 'Enter location',

//Subscribe

subscribe: 'Subscribe',
connectSouqSubscriptionPlans: 'Connect Souq Subscription Plans',
chooseSubscriptionPlan: 'Choose the subscription plan that suits you & your business best.',
mostPopular: 'Most Popular',
bronze: 'Bronze',
silver: 'Silver',
gold: 'Gold',
diamond: 'Diamond',
purchase: 'Purchase',
validity: 'Validity',
months: 'Months',
unlimited: 'Unlimited'

};

export const urdu = {
  login: "لاگ ان",
  BusinessPartner: "کاروباری شراکت دار کے طور پر سائن اپ کریں ",
  welcome:''
};

export const french = {
    login:'Connexion',
    BusinessPartner:'Inscrivez-vous en tant que partenaire',
    welcome:'Salut, bienvenue de retour',
    placeholder:'Entrez votre e-mail/téléphone',
    email:'Email/téléphone',
    password:'Mot de passe',
    frpassword:"Mot de passe oublié",
    next:"Suivant",
    SignIn:'Se connecter',
    SignGoogle:'Se connecter avec Google',
    CreatenewAccount:`Vous n'avez pas encore de compte ?` ,
    CreatenewAccount1:`Rejoignez Connect Souq dès maintenant !`,
    personalInformation: 'Informations personnelles',
    personalDetails: 'Informations personnels',
    enterPersonalDetails: 'Veuillez saisir vos coordonnées personnelles!',
    firstName: 'Prénom *',
    enterFirstName: 'Entrez votre prénom',
    lastName: 'Nom de famille',
    enterLastName: 'Entrez votre nom de famille',
    dateOfBirth: 'Date de naissance *',
    back: 'Retour',
    continue: 'Continuer',
    contactDetail: 'Détails de Contact',
    enterContactDetails: 'Veuillez entrer vos coordonnées de contact!',
    phoneNumber: 'Numéro de Téléphone',
    emailAddress: 'Email *',
    enterEmailAddress: 'Veuillez entrer votre emplacement personnel',
    personalLocation: 'Pays',
    selectCountry: 'Sélectionnez un pays',
    city: 'Ville *',
    enterCity: 'Entrez votre ville',
    register: 'S\'inscrire',
    registrationSuccessful: 'Inscription réussie',
    enterOTP: 'Entrez OTP',
    enterYourOTP: 'Entrez votre OTP',
    verifyOTP: 'Vérifier OTP',
    emailAlreadyRegistered: 'Email déjà enregistré',
    // 
    businessInfo: 'Informations professionnelles',
    individualCompany: 'Individu / Société',
    enterBusinessInfo: 'Veuillez saisir vos informations professionnelles!',
    individual: 'Individu',
    company: 'Société',
    previous: 'Précédent',
    continueBtn: 'Continuer',
    location: 'Emplacement',
    enterBusinessLocation: 'Veuillez entrer l\'emplacement de votre entreprise!',
    state: 'État',
    enterState: 'Entrez votre état',
    industry: 'Industrie',
    enterBusinessIndustry: 'Veuillez entrer l\'industrie de votre entreprise',
    companyDetails: 'Veuillez saisir les détails de votre entreprise',
    companyName: 'Nom de l\'entreprise',
    enterCompanyName: 'Saisissez le nom de votre entreprise',
    enterPostalCode: 'Saisissez votre code postal',
    businessContact: 'Contact professionnel',
    enterBusinessContact: 'Saisissez vos coordonnées professionnelles',
    businessEmail: 'E-mail professionnel',
    enterBusinessEmail: 'Saisissez votre e-mail professionnel',
    annualIncome: 'Revenu annuel',
    enterAnnualIncome: 'Saisissez votre revenu annuel',
    companySize: 'Taille de l\'entreprise',
    enterCompanySize: 'Saisissez la taille de votre entreprise',
    otherIndustry: 'Autre industrie',
    enterOtherIndustry: 'Saisissez une autre industrie',
    selectMinimumIndustries: 'Veuillez sélectionner au moins 5 industries',
    enterMandatoryFields: 'Veuillez saisir les champs obligatoires',
    // 
  userDetails: 'Détails de l\'utilisateur',
  addEmail: 'Ajouter un e-mail',
  emails: 'Email',
  enterEmail: 'Entrez votre e-mail',
  addContact: 'Ajouter un contact',
  contact: 'Contact',
  enterContact: 'Entrez votre contact',
  addWebsite: 'Ajouter un site Web',
  website: 'Site Web',
  enterWebsite: 'Entrez votre site Web',
  loginToContinue: 'Se connecter pour continuer',
  contactbusiness:'POUR DEVENIR PARTENAIRE CONNECTEUR, VOUS DEVEZ AJOUTER 1 CONTACT POTENTIEL COMME RÉFÉRENCE ET LE CONTACT SERA VÉRIFIÉ',
  bankDetails: 'Coordonnées bancaires',
  transitNumber: 'Numéro de transit',
  institutionNumber: 'Numéro d\'institution',
  accountNumber: 'Numéro de compte',
  certifyBankDetails: 'Je certifie que les coordonnées bancaires fournies sont correctes',
  enterdesignation:'Entrez votre Désignation',
  designation:'Désignation',
  registerDetails:`Veuillez entrer vos détails d'utilisateur!`,
//
  home: 'Accueil',
  searchHere: 'Rechercher ici',
  news: 'Actualités',
  advertisement: 'Publicité',
  post: 'Post',
  about: 'À propos',
  helpCenter: 'Centre d\'aide',
  privacyTerms: 'Confidentialité et conditions',
  adChoices: 'Choix publicitaires',
  advertising: 'Publicité',
  businessServices: 'Services professionnels',
  getApp: 'Obtenez l\'application',
  more: 'Plus',
  seeAll: 'Voir tout',
  whatsOnYourMind: 'Qu\'avez-vous en tête?',
  like: 'J\'aime',
  comment: 'Commentaire',
  share: 'Partager',
  complete: 'Complet',
  myItems: 'Mes articles',
  management: 'Gestion',
  logout: 'Se déconnecter',
  tryPremiumFor: 'Essayer Premium pour',
  see: 'Voir',
  // business-page

  business: 'Entreprise',
  search: 'Rechercher',
  chats: 'Discussions',
  group: 'Groupe',
  reply: 'Répondre',
  letsConnect: 'Connectons-nous',
  filters: 'Filtres',
  selectIndustry: 'Sélectionnez l\'Industrie',
  sales: 'Ventes',
  rating: 'Évaluation',
  sortBy: 'Trier par',
  showResults: 'Afficher les résultats',

  //pavilion

  gPavilion: 'G-Pavillon',
  selectCategory: 'Sélectionner une catégorie',
  viewDetails: 'Voir les détails',
  buyer: 'Acheteur',
  supplier: 'Fournisseur',
  enterLocation: 'Entrer l\'emplacement',

  // Subcribe

  subscribe: 'S\'abonner',
  connectSouqSubscriptionPlans: 'Plans d\'abonnement Souq',
  chooseSubscriptionPlan: 'Choisissez le plan d\'abonnement qui vous convient le mieux, ainsi qu\'à votre entreprise.',
  mostPopular: 'Le plus populaire',
  bronze: 'Bronze',
  silver: 'Argent',
  gold: 'Or',
  diamond: 'Diamant',
  purchase: 'Acheter',
  validity: 'Validité',
  months: 'Mois',
  unlimited: 'Illimité'

}



