const pagedata =[
"CS UAE",
"CS UK ",
"CS Kuwait",
"CS France",
"CS Baltic Region Group",
"CS Indonesia",
"CS Bangladesh Chapter",
"CS Singapore",
"CS Algeria",
"CS Argentina",
"CS Egypt",
"CS GHANA CHAPTER",
"CS Nigeria",
"CS Srilanka",
"CS Jamaica",
"CS USA",
"CS Pakistan",
"CS South Africa",
"CS Malaysia",
"CS Somailand",
"CS NewZealand",
"CS Qatar",
"CS Turkiye",
"CS Vietnam",
"CS Brazil",
"CS Neatherlands",
"CS Sierra Leone",
"CS Cologne",
"CS Bolivia",
"CS Paraguay",
"CS Guinea Bissau",
"CS Germany",
"CS Phillipines",
"CS Chile",
"CS Caribbean Islands",
"CS Italy",
"CS Gambia",
"CS Dar es salaamTanzania",
"CS Global Africa Summit",
"CS Oman",
"CS MP India",
"CS Karnataka",
"CS Hyderabad",
"CS Mumbai",
"CS Bengaluru",
"CS Delhi NCR",
"CS Haryana",
"CS Gujarat",
"CS Birmingham UK",
"CS Bostan USA",
"CS Kashmir",
"CS UP India",
"CS Istanbul",
"CS Konya",
"CS Africa Leadership Team",
"CS Agro Business",
"CS Mentor Mentee",
"CS Education Sector",
"CS IT Business",
"CS Healthcare and Medicine Business",
"CS Food Business",
"CS Video creative team",
"CS Apparels and Textiles",
"CS Electronics Business",
"CS Islamic Banking, Finance",
"CSOil and Gas Business",
"CS Design creative team",
"CS Building Material Business",
"CS Halal Retail Business",
"CS Startup Talent Hunt",
"CS Investors group",
"CS LAW & LEGAL INFORMATION",
"CS Construction and Building",
"CS Fisheries Business",
"CS Islamic Fintech Business",
"CS Engineers and Builders",
"CS Halal Travel and Tourism",
"CS Luxury & Niches",
"CS Media Communication",
"CS Recruitment and Consultancy Buisness",
]

